apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

commonLabels:
  purpose: Inception-demo
  env : Prod

replicas:
 - name: productcatalogue
   count: 3
 - name: shopfront
   count: 3

patches:
#  - target:
#      kind: Service
#      name: productcatalogue
#    patch: |-
#      - op: replace
#        path: /spec/ports/0/port
#        value: 8031
#  - target:
#      kind: Service
#      name: shopfront
#    patch: |-
#      - op: replace
#        path: /spec/ports/0/port
#        value: 8030
  - target:
      kind: Deployment
      name: productcatalogue
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: 'ruchabhange/productcatalouge-image:1cdc4ae496745d8291e20c00758170d052de7cb7'
  - target:
      kind: Deployment
      name: shopfront
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: 'ruchabhange/shopfront-image:1cdc4ae496745d8291e20c00758170d052de7cb7'

